name: "Deploy Case Study"

on:
  push:

env:
  PROJECT_PATH: Case_study_r0851784/Case_study_r0851784.csproj

jobs:
   deploy:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-dotnet@6.0.x
          with:
            dotnet-version: 6.0

        - run: dotnet restore ${{ env. PROJECT_PATH }}

        - run: dotnet build ${{ env. PROJECT_PATH }} -c Release --no-restore

        - run: dotnet publish ${{ env. PROJECT_PATH }} -c Release --self-contained -r win-x64 p:PublishSingleFile=true --no--build

        - uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - uses: csexton/release-asset-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pattern: Case_study_r0851784/bin/Release/net6.0-windows/win-x64/publish/*.exe
            release-url: ${{ steps.create_release.outputs.upload_url }}